mkx: v2.27 - 支持自动生成(完整依赖)makefile，实现自动/增量编译

diff --git a/mkx/mk b/mkx/mk
--- a/mkx/mk
+++ b/mkx/mk
@@ -18,6 +18,13 @@
 #     2015/12/11: 支持目录递归、编译前/后自定义命令
 #     2016/01/29: 支持自定义make选项, 配置名称: make-flags
 #                 (允许静态配置[文本]或者动态配置[命令])
+#     2016/01/31: 支持自动生成(完整依赖)makefile(默认关闭)，使用生成的
+#                 makefile进行(自动增量)编译;
+#                 配置方式:
+#                 using-mkx-makefile = yes
+#                 makefile-tpl-path = /path/to/mkxrc_makefiletpl
+#                 模板预定义变量:
+#                 用户当前使用makefile: {_origin_makefile_}
 #
 ############################################################
 
@@ -69,10 +76,72 @@ cd "$pwd"
 makeflags="`mkm get config make-flags`"
 mklog debug "make-flags:[$makeflags]"
 
-# make targets
-eval make $makeflags $* $targets
+# cleanup cmdline's -f/--file/--makefile option
+cmdline="`echo "$*" | sed -e 's/--makefile[ \t]*[^ \t]*//g' \
+                          -e 's/--file[ \t]*[^ \t]*//g' \
+                          -e 's/-f[ \t]*[^ \t]*//g'`"
+
+# get current makefile
+makefile="`make $* $targets -n -p | grep '^MAKEFILE_LIST' | awk '{printf $3}'`"
+
+# do not using mkx makefile until you say yes
+using_mkx_makefile="`mkm get config using-mkx-makefile`"
+mklog debug "using mkx makefile:[$using_mkx_makefile]"
+if [ "$using_mkx_makefile" = "yes" ] ; then
+    # prepare makefile for ...
+    makefile_org="$makefile"
+    makefile_mkx=".$makefile_org.mkx"
+    makefile_dep="$makefile_mkx"
+    makefile="$makefile_mkx"
+
+    # gen mkx makefile with tpl
+    if [ ! -f $makefile_dep ] ; then
+        # always cleanup and premake 'by user by user by user'
+        # for gen all deps from org makefile
+        # when mkx makefile not exist (by mkc)
+        # or mkx makefile tpl changed (by user)
+        # eg: run mkc && run pre-make
+        makefile_dep=$makefile_org
+
+        # gen new mkx makefile from tpl
+        makefile_tpl_path="`mkm get config makefile-tpl-path`"
+        mklog debug "makefile tpl path:[$makefile_tpl_path]"
+        if [ -z "$makefile_tpl_path" ] ; then
+            mklog error "makefile tpl path config not found, config key:[makefile_tpl_path]"
+            exit 1
+        fi
+        if [ ! -f "$makefile_tpl_path" ] ; then
+            mklog error "makefile tpl not found or empty, path:[$makefile_tpl_path]"
+            exit 1
+        fi
+        cp -f "$makefile_tpl_path" $makefile_mkx
+        sed -i "s/{_origin_makefile_}/$makefile_org/g" $makefile_mkx
+    fi
+
+    # update targets's deps into mkx makefile
+    mklog tip "generate deps for"
+    make -f $makefile_dep $cmdline $targets -n | grep -P "(g++|gcc).*\.o$" | while read mkcmd ; do
+        # get deps with -MM (user defined dep)
+        depcmd="`echo -n "$mkcmd" | sed 's/-o[ \t]*[^ \t]*/-MM/'`"
+        dep="`eval $depcmd | tr -d '\\\\\n'`"
+
+        # update deps (generally speaking, $name will not empty here)
+        name="`echo -n "$dep" | cut -d: -f1`"
+        sed -i "/$name/d" $makefile_mkx
+        echo "$dep" >> $makefile_mkx
+
+        # progress
+        mklog tip " $name"
+    done
+    echo
+fi
+
+# make targets with user-makefile or mkx-makefile in $makefile
+make="make -f $makefile $makeflags $cmdline $targets"
+mklog debug "make command:[$make]"
+eval $make
 if [ $? -ne 0 ] ; then
-    mklog error "make fail, make args:[$makeflags $* $targets]"
+    mklog error "make fail, make command:[$make]"
     exit 1
 fi
 
