mkx: v2.6 - mks/mkt/mkr支持目录递归(查找target)

diff --git a/mkx/mkr b/mkx/mkr
--- a/mkx/mkr
+++ b/mkx/mkr
@@ -7,7 +7,7 @@
 #
 # SYNOPSIS
 #     mkr
-#     mkr [ -f makefile ] [ -C directory ] [ targets ] ...
+#     mkr [ -f makefile ] [ targets ] ...
 # 
 #     debug=on mkr ...
 #
@@ -22,6 +22,7 @@
 # VERSION
 #     2015/11/21: 简单封装mkrun，支持重启
 #                 命令行或者makefile中OUTPUT定义的target
+#     2015/12/03: 支持目录递归查找target
 #
 ############################################################
 
@@ -30,6 +31,38 @@ if ! which mkrun >/dev/null 2>&1
 then
     mklog error "mkrun not found"
     exit 1
+fi
+
+# get make directory
+makedir="`make $* -n -p 2>/dev/null | grep '^CURDIR :=' | tail -n1 | cut -c11-`"
+if [ -z "$makedir" ] ; then
+    mklog error "make directory not found, make args:[$*]"
+    exit 1
+fi
+mklog debug "makedir=$makedir"
+
+# maybe mkr for sub directorys
+submakedirs="`make $* -n -p 2>/dev/null | grep '^DIRS =' | tail -n1 | cut -c8-`"
+mklog debug "submakedirs=$submakedirs"
+if [ -n "$submakedirs" ] ; then
+    for subdir in $submakedirs
+    do
+        mkrdir=""
+        if [ "${subdir:0:1}" = "/" ] ; then
+            mkrdir="$subdir"
+        else
+            mkrdir="$makedir/$subdir"
+        fi
+
+        pwd="`pwd`"
+        echo "mkr: Entering directory '$mkrdir'"
+        cd "$mkrdir"
+        mkr
+        echo "mkr: Leaving directory '$mkrdir'"
+        cd "$pwd"
+    done
+    mklog debug "mkr for directorys end"
+    exit 0
 fi
 
 # get targets from cmdline
@@ -44,6 +77,7 @@ then
     mklog error "targets not found, make args:[$*]"
     exit 1
 fi
+mklog debug "targets;[$targets]"
 
 # run target's restart command
 mkrun restart $targets
diff --git a/mkx/mks b/mkx/mks
--- a/mkx/mks
+++ b/mkx/mks
@@ -7,7 +7,7 @@
 #
 # SYNOPSIS
 #     mks
-#     mks [ -f makefile ] [ -C directory ] [ targets ] ...
+#     mks [ -f makefile ] [ targets ] ...
 # 
 #     debug=on mks ...
 #
@@ -22,6 +22,7 @@
 # VERSION
 #     2015/11/21: 简单封装mkrun，支持启动
 #                 命令行或者makefile中OUTPUT定义的target
+#     2015/12/03: 支持目录递归查找target
 #
 ############################################################
 
@@ -30,6 +31,38 @@ if ! which mkrun >/dev/null 2>&1
 then
     mklog error "mkrun not found"
     exit 1
+fi
+
+# get make directory
+makedir="`make $* -n -p 2>/dev/null | grep '^CURDIR :=' | tail -n1 | cut -c11-`"
+if [ -z "$makedir" ] ; then
+    mklog error "make directory not found, make args:[$*]"
+    exit 1
+fi
+mklog debug "makedir=$makedir"
+
+# maybe mks for sub directorys
+submakedirs="`make $* -n -p 2>/dev/null | grep '^DIRS =' | tail -n1 | cut -c8-`"
+mklog debug "submakedirs=$submakedirs"
+if [ -n "$submakedirs" ] ; then
+    for subdir in $submakedirs
+    do
+        mksdir=""
+        if [ "${subdir:0:1}" = "/" ] ; then
+            mksdir="$subdir"
+        else
+            mksdir="$makedir/$subdir"
+        fi
+
+        pwd="`pwd`"
+        echo "mks: Entering directory '$mksdir'"
+        cd "$mksdir"
+        mks
+        echo "mks: Leaving directory '$mksdir'"
+        cd "$pwd"
+    done
+    mklog debug "mks for directorys end"
+    exit 0
 fi
 
 # get targets from cmdline
@@ -44,6 +77,7 @@ then
     mklog error "targets not found, make args:[$*]"
     exit 1
 fi
+mklog debug "targets:[$targets]"
 
 # run target's start command
 mkrun start $targets
diff --git a/mkx/mkt b/mkx/mkt
--- a/mkx/mkt
+++ b/mkx/mkt
@@ -7,7 +7,7 @@
 #
 # SYNOPSIS
 #     mkt
-#     mkt [ -f makefile ] [ -C directory ] [ targets ] ...
+#     mkt [ -f makefile ] [ targets ] ...
 # 
 #     debug=on mkt ...
 #
@@ -22,6 +22,7 @@
 # VERSION
 #     2015/11/21: 简单封装mkrun，支持关闭
 #                 命令行或者makefile中OUTPUT定义的target
+#     2015/12/03: 支持目录递归查找target
 #
 ############################################################
 
@@ -30,6 +31,41 @@ if ! which mkrun >/dev/null 2>&1
 then
     mklog error "mkrun not found"
     exit 1
+fi
+
+# get make directory
+makedir="$directory"
+if [ -z "$makedir" ] ; then
+    makedir="`make $* -n -p 2>/dev/null | grep '^CURDIR :=' | tail -n1 | cut -c11-`"
+    if [ -z "$makedir" ] ; then
+        mklog error "make directory not found, make args:[$*]"
+        exit 1
+    fi
+    mklog debug "makedir=$makedir"
+fi
+
+# maybe mkt for sub directorys
+submakedirs="`make $* -n -p 2>/dev/null | grep '^DIRS =' | tail -n1 | cut -c8-`"
+mklog debug "submakedirs=$submakedirs"
+if [ -n "$submakedirs" ] ; then
+    for subdir in $submakedirs
+    do
+        mktdir=""
+        if [ "${subdir:0:1}" = "/" ] ; then
+            mktdir="$subdir"
+        else
+            mktdir="$makedir/$subdir"
+        fi
+
+        pwd="`pwd`"
+        echo "mkt: Entering directory '$mktdir'"
+        cd "$mktdir"
+        mkt
+        echo "mkt: Leaving directory '$mktdir'"
+        cd "$pwd"
+    done
+    mklog debug "mkt for directorys end"
+    exit 0
 fi
 
 # get targets from cmdline
@@ -44,6 +80,7 @@ then
     mklog error "targets not found, make args:[$*]"
     exit 1
 fi
+mklog debug "targets:[$targets]"
 
 # run target's stop command
 mkrun stop $targets
